Repository hiero-ledger/hiero-local-node, pull requests merged in 2022-10, with the labels that each got.

#174 Windows Issues
  README.md
  cli.js
  src/helpers/dockerCheck.js
  src/utils/constants.js
  src/utils/nodeController.js
Labels: Bug

#184 Local Node accepts TX > 6kb
  configs/local.json
  configs/mainnet.json
  configs/previewnet.json
  configs/testnet.json
  src/utils/nodeController.js
  templates/settings.txt
Labels: Feature Enhancement

#173 Smoke Tests CI
  .github/workflows/smoke-tests.yaml
  .npmignore
  package-lock.json
  package.json
  test/.gitignore
  test/hardhat.config.js
  test/package-lock.json
  test/package.json
  test/test/Smoke.js
Labels: Improvement

#179 Improve readme
  README.md
Labels: Feature Enhancement

#187 Integrate Hash Scan
  README.md
  configs/local.json
  configs/mainnet.json
  configs/previewnet.json
  configs/testnet.json
  docker-compose.yml
  templates/.env.template
  templates/local/.env.template
Labels: New Feature

#203 Fix local node occasionally fails to start
  cli.js
  package-lock.json
  package.json
Labels: Bug, P1
