Repository hiero-ledger/hiero-local-node, pull requests merged in 2023-06, with the labels that each got.

#343 Fix Account Generation
  cli.js
  src/utils/accountService.js
Labels: Bug

#331 Add support for user Compose definitions
  cli.js
  src/utils/cliOptions.js
  src/utils/nodeController.js
Labels: New Feature, Docker

#344 Optimize container startup order for better stability
  docker-compose.yml
Labels: Improvement

#325 Add json-rpc-relay metrics
  compose-network/grafana/dashboards/json-rpc-relay/default-prom.json
  compose-network/prometheus/prometheus.yml
Labels: P2, Feature Enhancement

#346 Fix cli argument parsing
  src/utils/nodeController.js
Labels: Bug

#350 Fix Docker Check error
  cli.js
  src/helpers/dockerCheck.js
  src/utils/constants.js
Labels: Bug
