Repository hiero-ledger/hiero-local-node, pull requests merged in 2023-11, with the labels that each got.

#420 Fix Terminal User Interface
  package-lock.json
  package.json
  src/data/StateData.ts
  src/services/CLIService.ts
  src/services/DockerService.ts
  src/services/LoggerService.ts
  src/state/AccountCreationState.ts
  src/state/AttachState.ts
  src/state/StartState.ts
  src/types/CLIOptions.ts
Labels: Limechain

#425 Bump Network images
  src/configuration/local.json
  src/configuration/mainnet.json
  src/configuration/previewnet.json
  src/configuration/testnet.json
Labels: Limechain

#424 Add recovery state
  src/controller/StateController.ts
  src/state/InitState.ts
  src/state/RecoveryState.ts
  src/state/StartState.ts
  src/types/EventType.ts
Labels: Limechain

#442 feat: add title check workflow
  .github/workflows/browser-tests.yaml
  .github/workflows/flow-pr-title-check.yaml
  .github/workflows/flow-pull-request-checks.yaml
  .github/workflows/smoke-tests.yaml
  .github/workflows/update-config-files.yaml
Labels: Limechain

#447 fix: Mirror Node Web3 ChainID configuration
  docker-compose.yml
Labels: Bug, Limechain

#448 chore: bump network images and local node version
  .env
  .github/workflows/flow-pull-request-checks.yaml
  README.md
  package-lock.json
  package.json
  src/configuration/local.json
  src/configuration/mainnet.json
  src/configuration/previewnet.json
  src/configuration/testnet.json
Labels: Release, Limechain

#451 fix: exit when unable to transition to next state
  src/controller/StateController.ts
Labels: Bug

#453 fix: bump web3 memory limit
  .env
  src/configuration/local.json
  src/configuration/mainnet.json
  src/configuration/previewnet.json
  src/configuration/testnet.json
Labels: Limechain
