Repository hiero-ledger/hiero-local-node, pull requests merged in 2023-04, with the labels that each got.

#310 docs: Updated Docker memory requirements
  README.md
  settings.png
Labels: P2

#312 Improve stability of local node
  README.md
  cli.js
  compose-network/mirror-node/application.yml
  compose-network/mirror-node/init.sh
  compose-network/network-node/data/onboard/GenesisPrivKey.txt
  compose-network/network-node/data/onboard/GenesisPubKey.txt
  compose-network/network-node/data/onboard/StartUpAccount.txt
  compose-network/network-node/data/onboard/addressBook.txt
  compose-network/network-node/data/onboard/devGenesisKeypair.pem
  compose-network/network-node/settings.txt
  docker-compose.evm.yml
  docker-compose.yml
  settings.png
  src/utils/nodeController.js
  templates/application.template.yml
  templates/local/application.template.yml
  templates/settings.txt
Labels: Improvement

#322 Fix Sonarcloud hotspots
  docker/main-network-node/Dockerfile
  docker/network-node-base/Dockerfile
  docker/network-node-haveged/Dockerfile
Labels: Improvement, Docker

#305 Add docs for different modes
  docs/evm-optimized.md
Labels: P2, Improvement, Performance
