Repository hiero-ledger/hiero-local-node, pull requests merged in 2023-12, with the labels that each got.

#461 fix: wrong ecdsa and ed25519 account generation
  package-lock.json
  package.json
  src/state/AccountCreationState.ts
Labels: Bug, Limechain

#462 fix: generate account options starting in attached mode
  src/services/CLIService.ts
Labels: Bug, Limechain

#463 feat: Improve account blocklisting feature
  package-lock.json
  package.json
  src/configuration/accountConfiguration.json
  src/constants.ts
  src/state/AccountCreationState.ts
Labels: Improvement, Limechain

#468 chore: Fix typos from previous pull request
  src/state/AccountCreationState.ts
Labels: Limechain

#469 chore: bump network images and version
  package-lock.json
  package.json
  src/configuration/local.json
  src/configuration/mainnet.json
  src/configuration/previewnet.json
  src/configuration/testnet.json
Labels: Release, Limechain

#471 fix: build before publishing to npm
  package.json
Labels: Bug, Release, Limechain

#472 Bump images and versions
  package-lock.json
  package.json
Labels: Release

#478 fix: Wrong startup account ids #474
  src/state/AccountCreationState.ts
Labels: Bug, Limechain

#481 fix: add missing healthcheck port for websocket relay
  docker-compose.yml
Labels: Bug, Limechain
