Repository hiero-ledger/hiero-local-node, pull requests merged in 2024-05, with the labels that each got.

#606 feat: expose ETH_CALL_DEFAULT_TO_CONSENSUS_NODE relay env in the local config file
  .env
  docker-compose.yml
  docs/environment-variables.md
  src/configuration/local.json
  src/configuration/previewnet.json
  src/configuration/testnet.json
Labels: Limechain

#613 chore: fix typescript warnings
  src/configuration/types/ITokenProps.ts
  src/utils/TokenUtils.ts
Labels: Limechain

#620 feat: Add CLI option for persistTransactionBytes
  compose-network/mirror-node/application.yml
  src/services/CLIService.ts
  src/state/InitState.ts
  src/types/CLIOptions.ts
  test/unit/states/InitState.spec.ts
Labels: P1, CLI, Limechain

#624 chore: remove deprecated Docker files
  .github/workflows/zxf-publish-docker-images.yaml
  docker/main-network-node/Dockerfile
  docker/main-network-node/entrypoint.sh
  docker/network-node-base/Dockerfile
  docker/network-node-haveged/Dockerfile
  docker/network-node-haveged/checksums/haveged_1.9.1-6ubuntu1_amd64.deb.sha256
  docker/network-node-haveged/checksums/haveged_1.9.1-6ubuntu1_arm64.deb.sha256
  docker/network-node-haveged/checksums/libhavege1_1.9.1-6ubuntu1_amd64.deb.sha256
  docker/network-node-haveged/checksums/libhavege1_1.9.1-6ubuntu1_arm64.deb.sha256
Labels: Release, Tech Debt Reduced
