Repository hiero-ledger/hiero-local-node, pull requests merged in 2024-06, with the labels that each got.

#639 feat: beatify logger
  package-lock.json
  package.json
  src/configuration/local.json
  src/configuration/mainnet.json
  src/configuration/previewnet.json
  src/configuration/testnet.json
  src/constants.ts
  src/controller/StateController.ts
  src/services/DockerService.ts
  src/services/LoggerService.ts
  src/state/AccountCreationState.ts
  src/state/CleanUpState.ts
  src/state/DebugState.ts
  src/state/InitState.ts
  src/state/ResourceCreationState.ts
  test/unit/states/AccountCreationState.spec.ts
  test/unit/states/CleanUpState.spec.ts
  test/unit/states/DebugState.spec.ts
  test/unit/states/InitState.spec.ts
Labels: P3, Improvement, Limechain

#643 feat: fix sdk dependency
  package-lock.json
  package.json
  src/configuration/local.json
  src/configuration/mainnet.json
  src/configuration/previewnet.json
  src/configuration/testnet.json
  test/smoke/package-lock.json
  test/smoke/package.json
Labels: Bug, P0, Limechain

#638 feat: expose opcodes endpoint by default
  .env
  compose-network/mirror-node/application.yml
  docker-compose.yml
  docs/custom-sub-system-configs.md
  test/unit/states/InitState.spec.ts
Labels: New Feature, P1, Limechain

#651 chore: bump network node tag to 0.51.0
  .env
  src/configuration/local.json
Labels: P1, Limechain

#652 chore: bump local node to 2.26.2
  package.json
Labels: P1, Limechain

#659 feat: Remove previewnet, testnet, mainnet configuration
  .github/workflows/flow-pull-request-checks.yaml
  README.md
  src/configuration/mainnet.json
  src/configuration/previewnet.json
  src/configuration/testnet.json
  src/data/ConfigurationData.ts
  src/services/CLIService.ts
  src/state/InitState.ts
  src/types/CLIOptions.ts
  src/types/NetworkType.ts
  test/unit/states/InitState.spec.ts
Labels: Limechain
