Repository hiero-ledger/hiero-local-node, pull requests merged in 2024-12, with the labels that each got.

#874 ci: Downgrade codecov-action to a stable version
  .github/workflows/flow-pull-request-checks.yaml
Labels: github_actions

#868 feat: deprecate `debug [timestamp]` command
  .env
  README.md
  docker-compose-state-migration.yml
  docker-compose.multinode.yml
  docker-compose.yml
  src/Errors/LocalNodeErrors.ts
  src/constants.ts
  src/data/StateData.ts
  src/index.ts
  src/services/CLIService.ts
  src/services/record-parser/parse.sh
  src/services/record-parser/record-parser.iml
  src/services/record-parser/src/META-INF/MANIFEST.MF
  src/services/record-parser/src/Parser.java
  src/services/record-parser/temp/.gitignore
  src/state/DebugState.ts
  src/state/InitState.ts
  src/types/CLIOptions.ts
  test/unit/states/DebugState.spec.ts
  test/unit/states/InitState.spec.ts
Labels: Improvement

#867 feat: add FAQ section
  README.md
Labels: Improvement

#878 chore: set default value of `scheduling.longTermEnabled` to `true`
  package-lock.json
  package.json
  src/configuration/local.json
Labels: dependencies
