Repository hiero-ledger/hiero-local-node, pull requests merged in 2024-08, with the labels that each got.

#723 fix: local node not starting with tag command
  .env
  package-lock.json
  package.json
  src/configuration/local.json
  src/state/InitState.ts
  test/cypress/package-lock.json
  test/cypress/package.json
Labels: Bug

#737 chore: Configure codecov and update CODEOWNERS
  .github/CODEOWNERS
  .github/workflows/flow-pull-request-checks.yaml
  codecov.yml
Labels: github_actions

#757 ci: update workflows to use latitude.sh based runners
  .github/workflows/flow-pr-title-check.yaml
  .github/workflows/flow-pull-request-checks.yaml
  .github/workflows/flow-semantic-release.yml
  .github/workflows/publish-npm-package.yaml
Labels: Feature Enhancement
