Repository hiero-ledger/hiero-local-node, pull requests merged in 2024-11, with the labels that each got.

#832 feat: JSON RPC Relay dashboards.
  compose-network/grafana/dashboards/json-rpc-relay/hedera-json-rpc-relay-http-server.json
  compose-network/grafana/dashboards/json-rpc-relay/webSocketServer.json
Labels: Feature Enhancement

#850 feat: add docker images start-up logger
  README.md
  src/constants.ts
  src/services/DockerService.ts
  src/state/StartState.ts
  src/state/StopState.ts
  test/unit/states/StopState.spec.ts
Labels: Improvement

#791 feat: Add Hedera Mirror Node Rest Java container
  compose-network/mirror-node/application.yml
  docker-compose.yml
Labels: Improvement, Docker
