Repository hiero-ledger/hiero-local-node, pull requests merged in 2024-01, with the labels that each got.

#479 feat: adds check for used ports
  package-lock.json
  package.json
  src/constants.ts
  src/services/DockerService.ts
  src/state/InitState.ts
Labels: Limechain

#485 fix: haveged container restarts
  docker-compose.yml
Labels: Bug

#473 feat: allow setting of working directory
  .env
  README.md
  docker-compose.yml
  src/constants.ts
  src/services/CLIService.ts
  src/state/CleanUpState.ts
  src/state/DebugState.ts
  src/state/InitState.ts
  src/state/StopState.ts
  src/types/CLIOptions.ts
  src/utils/FileSystemUtils.ts
Labels: Bug, New Feature, CLI

#483 feat: 434 add jsdocs
  src/Errors/LocalNodeErrors.ts
  src/controller/IObserver.ts
  src/controller/StateController.ts
  src/data/ConfigurationData.ts
  src/data/StateData.ts
  src/index.ts
  src/services/Bootstrapper.ts
  src/services/CLIService.ts
  src/services/ClientService.ts
  src/services/ConnectionService.ts
  src/services/DockerService.ts
  src/services/IService.ts
  src/services/LoggerService.ts
  src/services/ServiceLocator.ts
  src/state/AccountCreationState.ts
  src/state/AttachState.ts
  src/state/CleanUpState.ts
  src/state/DebugState.ts
  src/state/IState.ts
  src/state/InitState.ts
  src/state/NetworkPrepState.ts
  src/state/RecoveryState.ts
  src/state/StartState.ts
  src/state/StopState.ts
  src/types/AccountType.ts
  src/types/CLIOptions.ts
  src/types/EventType.ts
  src/types/NetworkConfiguration.ts
  src/types/NetworkType.ts
  src/types/StateConfiguration.ts
  src/types/VerboseLevel.ts
  src/utils/config.ts
  test.txt
Labels: Feature Enhancement

#498 chore: update copyright header
  .github/workflows/flow-pr-title-check.yaml
  .github/workflows/flow-pull-request-checks.yaml
  src/Errors/LocalNodeErrors.ts
  src/constants.ts
  src/controller/IObserver.ts
  src/controller/StateController.ts
  src/data/ConfigurationData.ts
  src/data/StateData.ts
  src/index.ts
  src/services/Bootstrapper.ts
  src/services/CLIService.ts
  src/services/ClientService.ts
  src/services/ConnectionService.ts
  src/services/DockerService.ts
  src/services/IService.ts
  src/services/LoggerService.ts
  src/services/ServiceLocator.ts
  src/state/AccountCreationState.ts
  src/state/AttachState.ts
  src/state/CleanUpState.ts
  src/state/DebugState.ts
  src/state/IState.ts
  src/state/InitState.ts
  src/state/NetworkPrepState.ts
  src/state/RecoveryState.ts
  src/state/StartState.ts
  src/state/StopState.ts
  src/types/AccountType.ts
  src/types/CLIOptions.ts
  src/types/EventType.ts
  src/types/NetworkConfiguration.ts
  src/types/NetworkType.ts
  src/types/StateConfiguration.ts
  src/types/VerboseLevel.ts
  src/utils/FileSystemUtils.ts
  src/utils/config.ts
Labels: Limechain

#489 docs: add multinode mode docs
  README.md
  docs/multinode-mode.md
Labels: CLI

#504 feat: Enhance Logger Service #497
  src/constants.ts
  src/services/CLIService.ts
  src/services/LoggerService.ts
  src/types/VerboseLevel.ts
Labels: Feature Enhancement, Improvement, CLI, Limechain

#506 fix: Running local-node occasionally fails on InitState
  src/services/DockerService.ts
Labels: Bug, Limechain

#509 feat: Create unit test for StopState #507
  package.json
  src/constants.ts
  src/state/StopState.ts
  test/unit/states/StopState.spec.ts
  test/unit/testBed.ts
Labels: Limechain

#512 feat: Create unit test for StartState #510
  src/constants.ts
  src/services/DockerService.ts
  src/state/StartState.ts
  src/state/StopState.ts
  test/unit/states/StopState.spec.ts
  test/unit/states/startState.spec.ts
  test/unit/testBed.ts
Labels: Limechain

#516 feat: Create unit test for RecoveryState #513
  src/constants.ts
  src/services/DockerService.ts
  src/state/RecoveryState.ts
  test/unit/states/StopState.spec.ts
  test/unit/states/recoveryState.spec.ts
  test/unit/states/startState.spec.ts
  test/unit/testBed.ts
Labels: Limechain

#526 feat: add options for custom tags
  README.md
  src/services/CLIService.ts
  src/state/InitState.ts
  src/types/CLIOptions.ts
Labels: Limechain

#518 feat: Create unit test for NetworkPrepState #515
  src/constants.ts
  src/state/NetworkPrepState.ts
  test/unit/states/networkPrepState.spec.ts
  test/unit/states/startState.spec.ts
  test/unit/testBed.ts
Labels: Limechain

#528 feat: Create unit test for InitState #521
  src/constants.ts
  src/data/ConfigurationData.ts
  src/state/InitState.ts
  test/unit/states/InitState.spec.ts
Labels: Limechain
