Repository hiero-ledger/hiero-local-node, pull requests merged in 2025-04, with the labels that each got.

#1003 chore: modify properties files in accordance with gradle spotless rules
  compose-network/network-node/data/config/api-permission.properties
  compose-network/network-node/data/config/application.properties
  compose-network/network-node/data/config/bootstrap.properties
Labels: github_actions

#1018 chore: Bump Heiro product versions to latest stable
  .env
  src/configuration/local.json
Labels: Improvement

#1021 chore: Bump local node package to v2.35
  package-lock.json
  package.json
Labels: Release
