Repository hiero-ledger/hiero-local-node, pull requests merged in 2025-05, with the labels that each got.

#1053 chore: Update MAINTAINERS.md
  MAINTAINERS.md
Labels: Improvement

#1031 fix: restore multinode mode functionality
  compose-network/mirror-node/application.yml
  compose-network/network-node/config.multinode.txt
  compose-network/network-node/data/keys/s-private-node2.pem
  compose-network/network-node/data/keys/s-private-node3.pem
  compose-network/network-node/data/keys/s-private-node4.pem
  compose-network/network-node/data/keys/s-public-node2.pem
  compose-network/network-node/data/keys/s-public-node3.pem
  compose-network/network-node/data/keys/s-public-node4.pem
  config.yaml
  docker-compose.multinode.yml
  src/configuration/originalNodeConfiguration.json
Labels: Bug

#1066 chore: hold the sdk version
  package-lock.json
  package.json
Labels: Bug

#1068 chore: release version 2.36.2
  package-lock.json
  package.json
  test/unit/states/AccountCreationState.spec.ts
  test/unit/utils/AccountUtils.spec.ts
Labels: Release

#1063 chore: Bump docker images to latest netowkr versions around 0.62.2
  .env
  config.yaml
  docker-compose.yml
  src/configuration/local.json
Labels: Improvement

#1084 chore: update images and packages
  package-lock.json
  package.json
  src/configuration/local.json
  src/services/CLIService.ts
  test/cypress/package-lock.json
  test/cypress/package.json
  test/smoke/package-lock.json
  test/smoke/package.json
Labels: Improvement

#1088 chore: revert mirror node explorer bump
  .env
  src/configuration/local.json
Labels: dependencies

#1092 chore: revert `block-node` enabled by default
  src/services/CLIService.ts
Labels: Regression

#1085 feat: improve devex in cli
  src/controller/StateController.ts
  src/state/InitState.ts
  test/unit/states/InitState.spec.ts
Labels: CLI

#1094 feat: Add Block Node support to multinode scenario
  .env
  compose-network/network-node/data/config/CNtoBNConfig/2to1/CN1/block-nodes.json
  compose-network/network-node/data/config/CNtoBNConfig/2to1/CN2/block-nodes.json
  config.yaml
  docker-compose.multinode.blocknode.yml
  docker-compose.multinode.yml
  docs/multinode-blocknode-overview.md
  docs/multinode-mode.md
  package-lock.json
  package.json
  src/configuration/local.json
  src/services/DockerService.ts
  test/smoke/package-lock.json
Labels: New Feature
