Repository hiero-ledger/hiero-local-node, pull requests merged in 2025-02, with the labels that each got.

#927 feat: pass java tool options
  .env
  docker-compose.yml
  src/state/InitState.ts
Labels: Bug

#930 feat: bump services to 0.59.0
  compose-network/network-node/config.txt
  compose-network/network-node/data/keys/private-node0.pfx
  compose-network/network-node/data/keys/private-node1.pfx
  compose-network/network-node/data/keys/private-node2.pfx
  compose-network/network-node/data/keys/private-node3.pfx
  compose-network/network-node/data/keys/public.pfx
  compose-network/network-node/data/keys/s-private-node1.pem
  compose-network/network-node/data/keys/s-public-node1.pem
  docker-compose.yml
  src/configuration/local.json
Labels: Improvement

#938 feat: edit error message for MacOS Docker's File Sharing error
  src/services/DockerService.ts
Labels: Improvement

#946 feat: use a locally built images in the local node
  src/services/DockerService.ts
Labels: Improvement

#950 chore: bump MN image to 0.124.0-rc1
  compose-network/mirror-node/application.yml
  src/configuration/local.json
Labels: Improvement

#942 ci: remove unrecognized brew update option in Smoke Tests
  .github/workflows/flow-pull-request-smoke-tests-on-macos.yaml
Labels: github_actions

#962 feat: add block node container
  .env
  README.md
  compose-network/grafana/dashboards/block-node/block-node-server.json
  compose-network/grafana/dashboards/block-node/cAdvisor.json
  compose-network/grafana/datasources/grafana_ds.yml
  compose-network/network-node/data/config/block-nodes.json
  compose-network/prometheus/prometheus.yml
  docker-compose.block-node.yml
  docker-compose.yml
  docs/environment-variables.md
  package-lock.json
  package.json
  src/configuration/local.json
  src/services/CLIService.ts
  src/services/DockerService.ts
  src/state/InitState.ts
  src/types/CLIOptions.ts
  test/unit/utils/SafeDockerNetworkRemover.spec.ts
Labels: Feature Enhancement, Improvement, Docker
